ALTER TABLE public.manifests DROP CONSTRAINT manifests_status_check;
ALTER TABLE public.manifests ADD CONSTRAINT manifests_status_check 
  CHECK (status = ANY (ARRAY['DRAFT','IN_PROGRESS','AWAITING_SIGNATURE','AWAITING_PAYMENT','AWAITING_RECEIVER_SIGNATURE','COMPLETED','VOIDED']));